apiVersion: v1
kind: Namespace
metadata:
  name: glowroot-apm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-pvc
  namespace: glowroot-apm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: glowroot-apm
  labels:
    app: cassandra
spec:
  clusterIP: None
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      name: cql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: glowroot-apm
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:5.0.4
        ports:
        - containerPort: 9042
          name: cql
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "GlowrootCluster"
        - name: CASSANDRA_DC
          value: "dc1"
        - name: CASSANDRA_RACK
          value: "rack1"
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: "SimpleSnitch"
        - name: CASSANDRA_SEEDS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JVM_EXTRA_OPTS
          value: "-Xmx1536M -Xms1024M -Xmn200M"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        livenessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 240
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 180
          periodSeconds: 15
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-data-pvc 