apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glowroot-data-pvc
  namespace: glowroot-apm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi 